### ISSUE TITLE
iOS Simulator Push Tokens incorrectly identified as GCM tokens

### ISSUE THREAD

**Issue by kvr-guestlogix** [appfeel/node-pushnotifications#188]
Since Xcode 14, iOS 16 simulators running on Apple Silicon now have the ability to register and receive push notifications. However, `getPushMethodByRegId()` is not capable for correctly identifying these tokens because they are more than 64 characters in length, and instead associates them as GCM tokens. 

As far as I know, it looks like simulator tokens are 160 characters long, but this is based solely on my own testing and I can't confirm the exact format. 

Is there any way to force the library to send via APN only? (I only have APN settings set in the constructor).

**Comment by miqmago** [comment]
Hi there, the issue here is with the length of the token. The triage of the method used to send push notifications is decided from token length. If it is longer than 64 characters (32 bytes) it is considered to be GCM, otherwise it is APNS (little more complex as there are other methods like web push and amazon). In simulators token is 160 characters long.

Problem is that android does not specify the length of the token and it seems it could be variable from 152 up to 4k, which includes 160!
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging#getToken()
https://groups.google.com/g/android-gcm/c/q2PzJTP71TY/m/DNX4lvDu5X4J

At this point, the solution that comes to my mind right now is to evaluate if the token is fully composed of [0-9A-Z], its length is even (not odd), and is 64 or 160.

Additionally we could support a regId object with the property `type` so we could pass a regId like this:

```json
{
  "id": "6ABF..."
  "type": "apn"
}
```

This is delicate issue as could break things... @alex-friedl what do you think?

**Comment by alex-friedl** [comment]
@miqmago If I understand correctly you suggest to drop the "auto-detect" of string tokens and have user's pass objects similar to the one you outlined in the comment, i.e. 

```json
{ "token": "string", "type": "string" }
```
where `type` is an enum of all supported providers, i.e. `apn`, `gcm`, `web` etc.?

If that's your suggestion I am all in favor of it, as it would get rid of these cases where the token is ambigious and be future-proof to changes on the provider side, as it would be agnostic of the token format.

The breaking change would not be a big issue, as we would of course release it as v 2.0 of the lib, therefore not breaking any users with 1.x
