### ISSUE TITLE
Body not working for Android

### ISSUE THREAD

**Issue by jpike88** [appfeel/node-pushnotifications#29]
{
    title: 'This Shows, // REQUIRED
    body: 'Uhhh should i show', // REQUIRED
    topic: 'some_stuff'
}

That body doesn't show in the android notification.

**Comment by appfeel** [comment]
Please see here: https://github.com/ToothlessGear/node-gcm/issues/279

**Comment by jpike88** [comment]
My pull request was probably rushed. But this is a design issue inherent in this library. It should be almost like a black box, where the most basic of arguments should achieve the desired effect.

That above data object worked fine with APNS, so why can't it work fine with GCM?

And what should that object be modified to, to achieve the desired result?

**Comment by appfeel** [comment]
The problem is with how google manages android push notifications, it's a mess. Could you show the code on your app? I can help you there.

Also you can see here how to get the data from the notification: https://github.com/appfeel/cordova-push-notifications/blob/master/src/android/com/plugin/gcm/GCMIntentService.java#L103

The main purpose of this library is the one you described, but we should not break old implementations. Maybe the changes you proposed could be integrated, not replacing the existing ones.

**Comment by jpike88** [comment]
It seems any time I touch something related to Google, it always leads into a mess. I'll tweak my android code to suit it and figure more out about what's going on here.

**Comment by jpike88** [comment]
What the hell. It now works. I didn't change anything today, just ran it again. Nice job Google.
