### ISSUE TITLE
GCM - FCM implementation doubt

### ISSUE THREAD

**Issue by ErnestoSalazar** [appfeel/node-pushnotifications#96]
Hello!, i wanted to ask if this module have the latest version of node-gcm implemented because of the changes from Google Cloud Messaging to Firebase Cloud Messaging.

__thanks in advance__

**Comment by alex-friedl** [comment]
Yes, the library uses the latest version of [node-gcm](https://github.com/ToothlessGear/node-gcm), which according to the README supports FCM since 0.14.1.

**Comment by guss77** [comment]
As far as I can tell, `node-gcm` cannot be used with new Firebase projects due to the fact that it doesn't support service tokens and isn't using the HTTPv1 API.

I think this project should instead change the GCM implementation to use `fcm-node` that supports service tokens and uses the new API, or just use `firebase-admin` directly instead (which is what `fcm-node` is using to implement new API support).
